Eliminate Solr missing content stream error
Solr 5.5 and Solr 6.6 report an error if there is no payload
  org.apache.solr.common.SolrException: missing content stream