Provide a fallback for a missing second date
If the record 008 date states a range of dates (q) but the second date is
missing, date2_str is undefined, and it causes an exception:

 Exception: NoMethodError: undefined method `sub' for nil:NilClass
 [...]/vendor/bundle/ruby/2.7.0/gems/traject-3.6.0/lib/traject/macros/marc21_semantics.rb:336:in
 `publication_date'

Assign date2_str the same value than date1_str as a fallback.